---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: bookshift

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    ldflags:
      - -s -w -X github.com/bjw-s-labs/bookshift/cmd.version={{.Version}}
  - id: darwin
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
    ldflags:
      - -s -w -X github.com/bjw-s-labs/bookshift/cmd.version={{.Version}}
  - id: kobo
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goos:
      - linux
    ldflags:
      - -s -w -X github.com/bjw-s-labs/bookshift/cmd.version={{.Version}}
    binary: usr/local/bookshift/bookshift
  - id: pocketbook
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goos:
      - linux
    ldflags:
      - -s -w -X github.com/bjw-s-labs/bookshift/cmd.version={{.Version}}
    binary: bookshift/bookshift

archives:
  - id: bookshift
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    ids:
      - linux
      - darwin
  - id: kobo
    name_template: "KoboRoot"
    ids:
      - kobo
    formats:
      - tgz
    files:
      - src: kobo/*
        dst: /
  - id: pocketbook
    name_template: "pocketbook"
    ids:
      - pocketbook
    formats:
      - tgz
    files:
      - src: pocketbook/*
        dst: /
      - src: config.yaml.dist
        dst: bookshift/config.yaml.dist

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request #\d+ from'
      - "^docs"
      - "^test"
